#pragma once

#include <bstorm/dnh_const.hpp>

#include <unordered_map>

namespace bstorm
{
const std::unordered_map<int, const char*> DIKeyNameMap
{
{ bstorm::KEY_ESCAPE, "Esc" },
{ bstorm::KEY_1, "1" },
{ bstorm::KEY_2, "2" },
{ bstorm::KEY_3, "3" },
{ bstorm::KEY_4, "4" },
{ bstorm::KEY_5, "5" },
{ bstorm::KEY_6, "6" },
{ bstorm::KEY_7, "7" },
{ bstorm::KEY_8, "8" },
{ bstorm::KEY_9, "9" },
{ bstorm::KEY_0, "0" },
{ bstorm::KEY_MINUS, "-" },
{ bstorm::KEY_EQUALS, "=" },
{ bstorm::KEY_BACK, "BackSpace" },
{ bstorm::KEY_TAB, "Tab" },
{ bstorm::KEY_Q, "Q" },
{ bstorm::KEY_W, "W" },
{ bstorm::KEY_E, "E" },
{ bstorm::KEY_R, "R" },
{ bstorm::KEY_T, "T" },
{ bstorm::KEY_Y, "Y" },
{ bstorm::KEY_U, "U" },
{ bstorm::KEY_I, "I" },
{ bstorm::KEY_O, "O" },
{ bstorm::KEY_P, "P" },
{ bstorm::KEY_LBRACKET, "[" },
{ bstorm::KEY_RBRACKET, "]" },
{ bstorm::KEY_RETURN, "Enter" },
{ bstorm::KEY_LCONTROL, "Ctrl Left" },
{ bstorm::KEY_A, "A" },
{ bstorm::KEY_S, "S" },
{ bstorm::KEY_D, "D" },
{ bstorm::KEY_F, "F" },
{ bstorm::KEY_G, "G" },
{ bstorm::KEY_H, "H" },
{ bstorm::KEY_J, "J" },
{ bstorm::KEY_K, "K" },
{ bstorm::KEY_L, "L" },
{ bstorm::KEY_SEMICOLON, ";" },
{ bstorm::KEY_APOSTROPHE, "'" },
{ bstorm::KEY_GRAVE, "`" },
{ bstorm::KEY_LSHIFT, "Shift Left" },
{ bstorm::KEY_BACKSLASH, "\\" },
{ bstorm::KEY_Z, "Z" },
{ bstorm::KEY_X, "X" },
{ bstorm::KEY_C, "C" },
{ bstorm::KEY_V, "V" },
{ bstorm::KEY_B, "B" },
{ bstorm::KEY_N, "N" },
{ bstorm::KEY_M, "M" },
{ bstorm::KEY_COMMA, "," },
{ bstorm::KEY_PERIOD, "." },
{ bstorm::KEY_SLASH, "/" },
{ bstorm::KEY_RSHIFT, "Shift Right" },
{ bstorm::KEY_MULTIPLY, "*" },
{ bstorm::KEY_LMENU, "Alt Left" },
{ bstorm::KEY_SPACE, "Space" },
{ bstorm::KEY_CAPITAL, "Caps Lock" },
{ bstorm::KEY_F1, "F1" },
{ bstorm::KEY_F2, "F2" },
{ bstorm::KEY_F3, "F3" },
{ bstorm::KEY_F4, "F4" },
{ bstorm::KEY_F5, "F5" },
{ bstorm::KEY_F6, "F6" },
{ bstorm::KEY_F7, "F7" },
{ bstorm::KEY_F8, "F8" },
{ bstorm::KEY_F9, "F9" },
{ bstorm::KEY_F10, "F10" },
{ bstorm::KEY_NUMLOCK, "Num Lock" },
{ bstorm::KEY_SCROLL, "Scroll Lock" },
{ bstorm::KEY_NUMPAD7, "NumPad 7" },
{ bstorm::KEY_NUMPAD8, "NumPad 8" },
{ bstorm::KEY_NUMPAD9, "NumPad 9" },
{ bstorm::KEY_SUBTRACT, "NumPad -" },
{ bstorm::KEY_NUMPAD4, "NumPad 4" },
{ bstorm::KEY_NUMPAD5, "NumPad 5" },
{ bstorm::KEY_NUMPAD6, "NumPad 6" },
{ bstorm::KEY_ADD, "NumPad +" },
{ bstorm::KEY_NUMPAD1, "NumPad 1" },
{ bstorm::KEY_NUMPAD2, "NumPad 2" },
{ bstorm::KEY_NUMPAD3, "NumPad 3" },
{ bstorm::KEY_NUMPAD0, "NumPad 0" },
{ bstorm::KEY_DECIMAL, "NumPad ." },
{ bstorm::KEY_F11, "F11" },
{ bstorm::KEY_F12, "F12" },
{ bstorm::KEY_F13, "F13" },
{ bstorm::KEY_F14, "F14" },
{ bstorm::KEY_F15, "F15" },
{ bstorm::KEY_KANA, "Kana" },
{ bstorm::KEY_CONVERT, "Convert" },
{ bstorm::KEY_NOCONVERT, "No Convert" },
{ bstorm::KEY_YEN, "Yen" },
{ bstorm::KEY_NUMPADEQUALS, "NumPad =" },
{ bstorm::KEY_CIRCUMFLEX, "^" },
{ bstorm::KEY_AT, "@" },
{ bstorm::KEY_COLON, ":" },
{ bstorm::KEY_UNDERLINE, "_" },
{ bstorm::KEY_KANJI, "Kanji" },
{ bstorm::KEY_STOP, "Stop" },
{ bstorm::KEY_AX, "AX" },
{ bstorm::KEY_UNLABELED, "Unlabeled" },
{ bstorm::KEY_NUMPADENTER, "NumPad Enter" },
{ bstorm::KEY_RCONTROL, "Ctrl Right" },
{ bstorm::KEY_NUMPADCOMMA, "NumPad ," },
{ bstorm::KEY_DIVIDE, "/" },
{ bstorm::KEY_SYSRQ, "Sys Rq" },
{ bstorm::KEY_RMENU, "Alt Right" },
{ bstorm::KEY_PAUSE, "Pause" },
{ bstorm::KEY_HOME, "Home" },
{ bstorm::KEY_UP, u8"Å™" },
{ bstorm::KEY_PRIOR, "Page Up" },
{ bstorm::KEY_LEFT, u8"Å©" },
{ bstorm::KEY_RIGHT, u8"Å®" },
{ bstorm::KEY_END, "End" },
{ bstorm::KEY_DOWN, u8"Å´" },
{ bstorm::KEY_NEXT, "Page Down" },
{ bstorm::KEY_INSERT, "Insert" },
{ bstorm::KEY_DELETE, "Delete" },
{ bstorm::KEY_LWIN, "Windows" },
{ bstorm::KEY_RWIN, "Windows" },
{ bstorm::KEY_APPS, "Menu" },
{ bstorm::KEY_POWER, "Power" },
{ bstorm::KEY_SLEEP, "Sleep" }
};
}